/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillMediumCircle,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";

import Image from "next/image";
import web from "../public/dev-figure.png";
import { informations as Informations } from "@/informations";
import Link from "next/link";
export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Zafer Barış</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">izbaris</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Zafer Barış
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Frontend Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              {Informations.description}
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href={Informations.github}>
                <AiFillGithub />
              </a>
              <a href={Informations.linkedin}>
                <AiFillLinkedin />
              </a>

              <a href={Informations.medium}>
                <AiFillMediumCircle />
              </a>
            </div>
            <img
              src={Informations.photo}
              className="rounded-full w-50 h-50  lg:h-80 lg:w-80 mx-auto mt-10"
              alt={"Author image"}
            />
          </div>
        </section>
        <section>
          <div>
            <h1 className="text-3xl py-1 dark:text-white ">
              Skills and Technologies
            </h1>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              With almost 3 years of experience, I am capable of understanding
              the requirements of an application and building it from scratch to
              the release stage. As I have worked on numerous use cases, I am
              familiar with most of the React Native packages. These packages
              include notifications, video calling and messaging applications,
              live GPS tracking, social media, IoT applications, e-commerce
              applications, and many others. In addition to this, I have
              utilized various project management tools for other aspects of the
              project.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="hover:shadow-2xl shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <h1 className="text-2xl font-medium pb-4">Technical skills</h1>
              <ol className="list-disc ml-2">
                <li className="text-gray-800 py-1">
                  TypeScript • React Native • React.js • Next.js • Node.js
                </li>
                <li className="text-gray-800 py-1">
                  Firebase Products (cloud messaging, push notifications, cloud
                  functions, firestore, realtime database, auth...)
                </li>
                <li className="text-gray-800 py-1">
                  Redux / Redux Saga / Redux Toolkit / React Query / Zustand...
                </li>
                <li className="text-gray-800 py-1">
                  Google Apis (Fit, Map, Places, Books...)
                </li>
                <li className="text-gray-800 py-1">
                  React Navigation / Gesture Handler / Animated / WebRTC /
                  WebSockets / i18n / Lottie...
                </li>
                <li className="text-gray-800 py-1">
                  Expo / React Native CLI / Xcode / Android Studio
                </li>
                <li className="text-gray-800 py-1">
                  React Native Testing Library / Jest / Detox
                </li>
                <li className="text-gray-800 py-1">Git • Github</li>
              </ol>
            </div>
            <div className="hover:shadow-2xl  shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <h1 className="text-2xl font-medium pb-4 ">
                Project Management Skills
              </h1>
              <ol className="list-disc ml-2">
                <li className="text-gray-800 py-1">
                  Creating project timelines
                </li>
                <li className="text-gray-800 py-1">Team leadership</li>
                <li className="text-gray-800 py-1">
                  Agile/Scrum methodologies
                </li>
                <li className="text-gray-800 py-1">
                  Creating project timelines Jira
                </li>
                <li className="text-gray-800 py-1">
                  Azure DevOps (CI/CD, pipelines)
                </li>
                <li className="text-gray-800 py-1">
                  Agile/Scrum methodologies
                </li>
              </ol>
            </div>
            <div className="hover:shadow-2xl  shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <h1 className="text-2xl font-medium pb-4 ">Soft Skills</h1>

              <ol className="list-disc ml-2">
                <li className="text-gray-800 py-1">
                  Communication (verbal and written)
                </li>
                <li className="text-gray-800 py-1">
                  Teamwork and collaboration
                </li>
                <li className="text-gray-800 py-1">
                  Problem-solving and critical thinking
                </li>
                <li className="text-gray-800 py-1">
                  Adaptability and flexibility
                </li>
                <li className="text-gray-800 py-1">Time management</li>
                <li className="text-gray-800 py-1">Leadership</li>
                <li className="text-gray-800 py-1">
                  Creativity and innovation
                </li>
              </ol>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">
              Personal Projects
            </h3>
            <p className="text-md pt-2 leading-8 text-gray-800 dark:text-gray-200">
              I have worked freelance for 5 months and full-time for over a
              year, with most of my experience being in the industry and on
              projects that cannot be shared due to confidentiality reasons. I
              have a few applications published but not in a market open to
              Turkey
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10">
            {Informations.projects.map((project, index) => (
              <Link key={index} href={project.url}>
                <div className="p-10 shadow-xl xl:flex flex-none rounded-lg">
                  <Image
                    className="rounded-lg 2xl:object-cover object-contain my-10 m-auto"
                    width={600}
                    height={300}
                    src={project.image}
                    alt={"project image"}
                  />
                  <div className="sm:mt-10 lg:ml-10 flex-1">
                    <p className="text-3xl dark:text-white mb-4">
                      {project.name}
                    </p>
                    <p className="dark:text-white mb-6 leading-8">
                      {project.description}
                    </p>
                    <p className="text-xl dark:text-white">Features</p>
                    <ol className="list-disc mb-6">
                      {project.features?.map((feature, index) => (
                        <li key={index} className="dark:text-white ml-4">
                          {feature}
                        </li>
                      ))}
                    </ol>
                    <h1 className="text-xl dark:text-white">Technologies</h1>
                    <ol className="list-disc">
                      {project.techStack?.map((tech, index) => (
                        <li key={index} className="dark:text-white ml-4">
                          {tech}
                        </li>
                      ))}
                    </ol>
                  </div>
                </div>
              </Link>
            ))}
          </div>
          <Link href={Informations.github} className="justify-center flex">
            <div className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white border-none rounded-lg text-center w-40 p-4 ">
              More on Github
            </div>
          </Link>
        </section>
      </main>
    </div>
  );
}
